### ISSUE TITLE
[new addon] zigbee-conbee-adapter

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/addon-list#146] opened 2018-11-01 11:45 UTC
Adapter using ConBee USB stick to access Zigbee devices.

```
{
    "name": "zigbee-conbee-adapter",
    "display_name": "Zigbee adapter ConBee USB stick",
    "description": "Adapter for Zigbee  using  ConBee USB stick",
    "version": "0.9.0",
    "url": "https://github.com/tomasy/zigbee-conbee-adapter/releases/download/0.9.0/zigbee-conbee-adapter-0.9.0.tgz",
     "api": {
      "min": 2,
      "max": 2
    }
}
```

PS.
Is it possible to change description for my DateTime Adapter
from _A DateTime adapter to create more advanced rules_ to
_A DateTime adapter to create more advanced rules, Supports e.g. sunrise, sunset, weekends,..._

**Comment by mrstegeman** [comment] 2018-11-01 11:48
@dhylands Can you weigh in on this?

@tomasy Yes, I can update the description.

**Comment by dhylands** [comment] 2018-11-01 16:08
Having alternate adapters seems reasonable to me.

I'm planning on adding support for RaspBee/Conbee to our zigbee adapter real soon now.

**Comment by dhylands** [comment] 2018-11-01 16:10
This adapter is really a deConz adapter rather than a ConBee adapter since it essentially interfaces to the deConz software stack through its REST API.

**Comment by mrstegeman** [comment] 2018-11-01 16:37
Maybe this should be renamed to deconz-adapter to be more clear to users?

**Comment by tomasy** [comment] 2018-11-01 19:30
I do not think people who have bought a ConeBee USB stick know that deconz-adapter support it.

I think it is good to be clear what type of hardware it support. When I bought ConBee I thought it was supported by Zigbee adapter but then I realize it just supported one other hardware.

But if you will support ConBee in a better way I can withdraw mine. Just one question must the USB be attached to the same pi that runs the gateway?

**Comment by mrstegeman** [comment] 2018-11-01 19:43
@tomasy That's why we have the `description` and `display_name` fields. 😄 

@dhylands can answer your other questions better than I can.

**Comment by dhylands** [comment] 2018-11-01 21:00
Supporting the deCONZ REST API still seems worthwhile to me. Some people might have one already setup and just want to try our gateway without having to reconfigure their entire network.

Currently, the gateway software needs to run on whatever machine that the ConBee is plugged into. I normally run the gateway on my linux laptop, but the way we distribute it is for the Pi.

**Comment by mrstegeman** [comment] 2018-11-02 13:15
@tomasy Ok, I've started reviewing the package.

1. You can remove `bootstrap.py`, since you're not actually bootstrapping anything. Just make `package.json` point to `main.py` instead of `bootstrap.py`.
2. Remove `requirements.txt`, `setup.cfg`, and `bootstrap.py` from `files` in `package.json`.
3. Add `pkg/conbee_action.py`, `pkg/conbee_config.py`, and `pkg/deconz_rest_api.py` to the `files` array.
4. Add-on crashes repeatedly on startup if configuration has not been done. This is not ideal. You should probably at least log something and exit gracefully.
    * If you exit with code 100, the add-on will not restart automatically.
    * Additionally, there is a `send_error()` method in the `AddonManagerProxy` which will display an error in the UI. You can get to that from the adapter via `adapter.manager_proxy.
    * In the config schema in `package.json`, both `url` and `apikey` should probably be marked as required by adding a `required` array to the `schema` field.
5. You should probably remove your API key from `conbee_config.py`.

The error I got on startup is:
```
2018-11-02 07:05:10.061 INFO   : zigbee-conbee: main.py:39 INFO Starting Zigbee Conbee Addon
2018-11-02 07:05:10.062 INFO   : zigbee-conbee: main.py:46 INFO Starting zigbee-conbee-adapter. gateway_addon.API_VERSION: 2
2018-11-02 07:05:10.062 INFO   : zigbee-conbee: main.py:47 INFO Arguments list: ['/Users/mstegeman/.mozilla-iot/addons/zigbee-conbee-adapter/main.py']
2018-11-02 07:05:10.062 INFO   : zigbee-conbee: IpcClient: Connected to server, registering...
2018-11-02 07:05:10.063 INFO   : zigbee-conbee: IpcClient: Received manager message: b'{"messageType":"registerPluginReply","data":{"pluginId":"zigbee-conbee-adapter","ipcBaseAddr":"gateway.plugin.zigbee-conbee-adapter"}}'
2018-11-02 07:05:10.063 INFO   : zigbee-conbee: IpcClient: Registered with PluginServer
2018-11-02 07:05:10.063 INFO   : zigbee-conbee: AddonManagerProxy: add_adapter: zigbee-conbee-adapter
2018-11-02 07:05:10.064 INFO   : zigbee-conbee: conbee_config.py:18 INFO config {'url': '', 'apikey': ''}
2018-11-02 07:05:10.065 INFO   : zigbee-conbee: conbee_adapter.py:29 INFO init ConBeeAdapter
2018-11-02 07:05:10.065 INFO   : zigbee-conbee: conbee_adapter.py:34 INFO START Pairing Lights
2018-11-02 07:05:10.070 INFO   : zigbee-conbee: EXECPTION
2018-11-02 07:05:10.070 INFO   : zigbee-conbee: unknown url type: '/api///lights'
2018-11-02 07:05:10.071 INFO   : zigbee-conbee: ("unknown url type: '/api///lights'",)
2018-11-02 07:05:10.071 INFO   : zigbee-conbee: ['Traceback (most recent call last):\n', '  File "/Users/mstegeman/.mozilla-iot/addons/zigbee-conbee-adapter/main.py", line 50, in <module>\n    _ADAPTER = ConBeeAdapter(verbose=True)\n', '  File "/Users/mstegeman/.mozilla-iot/addons/zigbee-conbee-adapter/pkg/conbee_adapter.py", line 30, in __init__\n    self.start_pairing(0)\n', '  File "/Users/mstegeman/.mozilla-iot/addons/zigbee-conbee-adapter/pkg/conbee_adapter.py", line 35, in start_pairing\n    json_dict = self.rest.get_lights()\n', '  File "/Users/mstegeman/.mozilla-iot/addons/zigbee-conbee-adapter/pkg/deconz_rest_api.py", line 34, in get_lights\n    json_response = urllib.request.urlopen(self.conbee_url + \'/lights\').read()\n', '  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen\n    return opener.open(url, data, timeout)\n', '  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 510, in open\n    req = Request(fullurl, data)\n', '  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 328, in __init__\n    self.full_url = url\n', '  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 354, in full_url\n    self._parse()\n', '  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 383, in _parse\n    raise ValueError("unknown url type: %r" % self.full_url)\n', "ValueError: unknown url type: '/api///lights'\n"]
2018-11-02 07:05:10.072 INFO   : zigbee-conbee: main.py:61 INFO STOPPED Zigbee Conbee Addon
2018-11-02 07:05:10.089 INFO   : Plugin: zigbee-conbee-adapter died, code = 0 restarting...
```

**Comment by tomasy** [comment] 2018-11-04 11:05
Fixed your comments, but I noticed that after a `send_error` and exit(100) the adapter is still enabled in the gateway. 
And a more serious problem. If I enable it I sometimes get a ` Segmentation fault` and the gateway restarted.
https://github.com/tomasy/zigbee-conbee-adapter/releases/download/0.9.1/zigbee-conbee-adapter-0.9.1.tgz

```
nov 04 11:42:02 gateway run-app.sh[4348]: 2018-11-04 11:42:02.504 zigbee-conbee: conbee_adapter.py:68 ERROR Problem during pairing of devices. Will exit. Execption: unknown url type: 's/api/E09EC9XXXX//lights'                    
nov 04 11:42:02 gateway run-app.sh[4348]: 2018-11-04 11:42:02.964 zigbee-conbee: AddonManagerProxy: Failed to send message: Bad file descriptor                                                                                      
nov 04 11:42:05 gateway run-app.sh[4348]: 2018-11-04 11:42:05.450 zigbee-conbee: conbee_adapter.py:89 INFO End unload all devices                           
nov 04 11:42:05 gateway run-app.sh[4348]: 2018-11-04 11:42:05.452 zigbee-conbee: AddonManagerProxy: Failed to send message: Nanomsg library was terminated          
nov 04 11:42:13 gateway run-app.sh[4348]: 2018-11-04 11:42:13.113 Plugin: zigbee-conbee-adapter died, code = 100 NOT restarting...                                                                                                                          
nov 04 11:42:31 gateway run-app.sh[4348]: 2018-11-04 11:42:31.192 Unloading ConBeeAdapter                                                                                                                                                           
nov 04 11:42:31 gateway run-app.sh[4348]: Segmentation fault                                                                                                       
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! code ELIFECYCLE                                                                                      
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! errno 139                                                                                                                                                              
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! things-gateway@0.6.1 start: `webpack && node build/gateway.js "--check-wifi"`                                   
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! Exit status 139                                                                                                             
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR!                                                                                                         
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! Failed at the things-gateway@0.6.1 start script.                                                                                                                                                            
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.            
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR! A complete log of this run can be found in:                                                                  
nov 04 11:42:31 gateway run-app.sh[4348]: npm ERR!     /home/pi/.npm/_logs/2018-11-04T10_42_31_282Z-debug.log                                                                                                              
nov 04 11:42:41 gateway systemd[1]: mozilla-iot-gateway.service: Service hold-off time over, scheduling restart.                                                                      
nov 04 11:42:41 gateway systemd[1]: Stopped Mozilla IoT Gateway Client.                                                                                                                                                                  
nov 04 11:42:41 gateway systemd[1]: Started Mozilla IoT Gateway Client.                                                                                                                                                        



/home/pi/.npm/_logs/2018-11-04T10_42_31_282Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/home/pi/.nvm/versions/node/v8.12.0/bin/node',
1 verbose cli   '/home/pi/.nvm/versions/node/v8.12.0/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--check-wifi' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle things-gateway@0.6.1~prestart: things-gateway@0.6.1
6 info lifecycle things-gateway@0.6.1~start: things-gateway@0.6.1
7 verbose lifecycle things-gateway@0.6.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle things-gateway@0.6.1~start: PATH: /home/pi/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/mozilla-iot/gateway/node_modules/.bin:/home/pi/.nvm/versions/node/v8.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u\
sr/bin:/sbin:/bin
9 verbose lifecycle things-gateway@0.6.1~start: CWD: /home/pi/mozilla-iot/gateway
10 silly lifecycle things-gateway@0.6.1~start: Args: [ '-c', 'webpack && node build/gateway.js "--check-wifi"' ]
11 silly lifecycle things-gateway@0.6.1~start: Returned: code: 139  signal: null
12 info lifecycle things-gateway@0.6.1~start: Failed to exec start script
13 verbose stack Error: things-gateway@0.6.1 start: `webpack && node build/gateway.js "--check-wifi"`
13 verbose stack Exit status 139
13 verbose stack     at EventEmitter.<anonymous> (/home/pi/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/pi/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid things-gateway@0.6.1
15 verbose cwd /home/pi/mozilla-iot/gateway
16 verbose Linux 4.14.30-v7+
17 verbose argv "/home/pi/.nvm/versions/node/v8.12.0/bin/node" "/home/pi/.nvm/versions/node/v8.12.0/bin/npm" "start" "--" "--check-wifi"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 139
22 error things-gateway@0.6.1 start: `webpack && node build/gateway.js "--check-wifi"`
22 error Exit status 139
23 error Failed at the things-gateway@0.6.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 139, true ]


```

**Comment by mrstegeman** [comment] 2018-11-05 18:33
I was unable to reproduce your error. However, a good workaround would be to check for the required configuration inside of `start_pairing()`. If it's not set, just return. Then you don't have to deal with exiting and whatnot.

All the other changes look good.

**Comment by tomasy** [comment] 2018-11-05 19:30
Changed. Will not terminate
https://github.com/tomasy/zigbee-conbee-adapter/releases/download/0.9.3/zigbee-conbee-adapter-0.9.3.tgz

**Comment by mrstegeman** [comment] 2018-11-05 19:54
Small patch request which will make things a little more user-friendly:

```patch
--- conbee_adapter.py.orig	2018-11-05 12:48:21.000000000 -0700
+++ conbee_adapter.py	2018-11-05 12:51:23.000000000 -0700
@@ -64,13 +64,10 @@
                     logging.info('Unknow sensor. Not added')
         except ValueError as ex:
             logging.exception('ERROR Exception %s', ex)
-            msg = 'Problem during pairing of devices. Will exit. Execption: {}'.format(ex)
-            logging.error(msg)
+            msg = 'Zigbee-Conbee Adapter: Problem during pairing of devices.'
             self.send_error(msg)
-            time.sleep(20)
         except Exception as ex:
             logging.exception('ERROR Exception %s', ex)
-            msg = 'Problem during pairing of devices. Execption: {}'.format(ex)

     def cancel_pairing(self):
          """Cancel pairing process."""
```

**Comment by tomasy** [comment] 2018-11-05 22:02
And...
https://github.com/tomasy/zigbee-conbee-adapter/releases/download/0.9.4/zigbee-conbee-adapter-0.9.4.tgz

**Comment by mrstegeman** [comment] 2018-11-05 22:16
@tomasy I opened a PR and found another error.

In your package, `display_name` is `Zigbee-Conbee Adapter`. However, what you requested above was `Zigbee (ConBee USB stick)`. These need to match.

**Comment by tomasy** [comment] 2018-11-05 22:39
Fixed
https://github.com/tomasy/zigbee-conbee-adapter/releases/download/0.9.5/zigbee-conbee-adapter-0.9.5.tgz

**Closed** 2018-11-06 13:07 UTC
Labels: review
