### ISSUE TITLE
The Google Home TTS adapter does not work

### ISSUE THREAD

**Issue by igilham** [mozilla-iot/addon-list#426] opened 2019-09-06 14:11 UTC
The [Google Home TTS adapter](https://github.com/mozilla-iot/addon-list/blob/master/addons/google-home-adapter.json) is broken and beyond useless. Consider removing it or at least making addon removal correctly clean up devices on removal.

**Comment by kgiori** [comment] 2019-09-06 15:40
I have been using the Google Home TTS adapter for a while. My two biggest issues so far:
1. if the G-home changes IP addresses, I have to remove and re-add it, which is a pain for all the rules I have against it
2. I wish there was a way to disable that "chime" sound 
Did you try a full "shift-reload" of the browser? Sometimes the UI connection needs a reload to display the correct thing states.

**Comment by tim-hellhake** [comment] 2019-09-06 16:45
@igilham, first of all, thank you for your feedback.
I would appreciate it if you would give me at least the chance to answer before considering it _broken and beyond useless_.
I'm doing this in my free time, so please be a little patient if I'm not responding within minutes.

**Comment by tim-hellhake** [comment] 2019-09-06 16:53
Duplicate of tim-hellhake/google-home-adapter#6

**Closed** 2019-09-06 17:01 UTC

**Comment by tim-hellhake** [comment] 2019-09-06 23:15
> if the G-home changes IP addresses, I have to remove and re-add it, which is a pain for all the rules I have against it

Sorry I wasn't aware of that.
I added a new issue: tim-hellhake/google-home-adapter#7

**Comment by igilham** [comment] 2019-09-09 09:23
@tim-hellhake Sorry, that was antagonistic and unhelpful. My reason for raising this here was that the addons list may benefit from not showing addons that don't work well yet, at least by default. Maybe one day there will be a 'supported' or 'tested' list and a way to add unsupported addons separately.

As far as I can tell, the gateway itself has a few reliability issues around adding and removing devices that seem to require a restart to fix. It isn't clear if the issue comes from the addon or from the gateway but it's always tempting to blame the newly installed component.

**Comment by kgiori** [comment] 2019-09-09 15:18
@tim-hellhake -- by the way, I am a huge fan of this add-on (and others you have written). I have pre-configured text strings tied to many rules. For example:
* to wish someone happy birthday when the door opens during certain hours of the day
* to announce when the baking timer elapses, to check the oven
* to announce earthquakes > 5.0 within 400km
* to wish "Happy Friday" after 4pm on Friday (when door opens)
* loud intruder warning when motion triggered when no one should be home 
* loud intruder warning when exterior back door opened during the night
* every minute it will warn us if the leak detector (under sink) changes to "wet"

In general, if the generic TTS add-on to the gateway (e.g., on RPi) didn't require extra install steps, it would likely replace my use of this one. Because my G-Home sits on mute, I have to walk over to it to unmute to ask it to stream music. So another question for you -- does the G-Home API allow network commands to have it stream Internet radio stations like your Internet Radio add-on? I added that "Internet Radio" add-on over the weekend and it has become another new favorite. I created simple 1-second pulses with names of the stations I like best, so I can use my voice (with voice-controller add-on) to say things like "turn on the radio", "turn on jazz", "turn on KQED". G-Home has better speaker quality, so being able to use it for music streaming via web things commands would be great too. (But I have yet to try the Chromecast add-on -- maybe that would do it.)

Anyway, you've built some amazingly useful add-ons, thanks!
